# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME, CONV(SKILL_CODE, 10, 2)
# FROM DEVELOPERS
# WHERE 0 IN CONV(SKILL_CODE, 10, 2) & 

# SELECT FIRST_NAME, LAST_NAME, CONV(SKILL_CODE, 10, 2), CONV(CODE,10,2),
# CASE WHEN SKILL_CODE >= CODE
# THEN CONV(SKILL_CODE, 10, 2) & CONV(CODE,10,2) 
# ELSE 0 END AS c
# FROM DEVELOPERS, (SELECT CODE FROM SKILLCODES WHERE CATEGORY = 'Front End') s

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT SUM(CODE)
                   FROM SKILLCODES
                   WHERE CATEGORY = 'Front End')
ORDER BY ID

# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME, c
# FROM (
#     SELECT
#         ID,
#         EMAIL,
#         FIRST_NAME, 
#         LAST_NAME, 
#         CONV(SKILL_CODE, 10, 2) AS skill_code_binary, 
#         CONV(CODE, 10, 2) AS code_binary,
#         CASE 
#             WHEN SKILL_CODE >= CODE THEN CONV(SKILL_CODE, 10, 2) & CONV(CODE, 10, 2) 
#             ELSE 0 
#         END AS c
#     FROM DEVELOPERS, (SELECT CODE FROM SKILLCODES WHERE CATEGORY = 'Front End') s
# ) subquery
# WHERE c > 0
# # GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME