-- 코드를 입력하세요
# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT a.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT a.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
# FROM ONLINE_SALE AS a
# LEFT OUTER JOIN USER_INFO AS b
# ON a.USER_ID = b.USER_ID
# WHERE a.USER_ID IN (SELECT USER_ID
#                  FROM USER_INFO
#                  WHERE JOINED LIKE '2021%')
# GROUP BY YEAR, MONTH

# SELECT COUNT(*)
# FROM USER_INFO
# WHERE JOINED LIKE '2021%'




# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT a.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT a.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
# FROM USER_INFO AS a
# JOIN ONLINE_SALE AS b
# ON a.USER_ID = b.USER_ID
# WHERE b.USER_ID IN (SELECT USER_ID
#                    FROM USER_INFO
#                    WHERE JOINED LIKE '2021%')
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH

WITH members AS (
    SELECT user_id
    FROM user_info
    WHERE 1=1
        AND joined LIKE '2021%'
)   
SELECT
    YEAR(sales_date) AS year,
    MONTH(sales_date) AS month,
    COUNT(DISTINCT user_id) AS purchased_users,
    ROUND(COUNT(DISTINCT user_id) / (SELECT COUNT(user_id) FROM members), 1) AS purchased_ratio
FROM online_sale
WHERE 1=1
    AND user_id IN (SELECT user_id FROM members)
GROUP BY YEAR(sales_date), MONTH(sales_date)
ORDER BY year, month