-- 코드를 입력하세요
# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT a.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT a.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
# FROM ONLINE_SALE AS a
# LEFT OUTER JOIN USER_INFO AS b
# ON a.USER_ID = b.USER_ID
# WHERE a.USER_ID IN (SELECT USER_ID
#                  FROM USER_INFO
#                  WHERE JOINED LIKE '2021%')
# GROUP BY YEAR, MONTH

# SELECT COUNT(*)
# FROM USER_INFO
# WHERE JOINED LIKE '2021%'




SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT a.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT a.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM USER_INFO AS a
JOIN ONLINE_SALE AS b
ON a.USER_ID = b.USER_ID
WHERE b.USER_ID IN (SELECT USER_ID
                   FROM USER_INFO
                   WHERE JOINED LIKE '2021%')
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH